package exception.try_catch_user_exception;

public class SimpleTest {
    public static void main(String[] args)  {

    }
}
